<?php
/**
 * AvailabilityTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EbayInventoryApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace EbayInventoryApi;

use PHPUnit\Framework\TestCase;

/**
 * AvailabilityTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used to specify the quantity of the inventory item that is available for purchase if the item will be shipped to the buyer, and the quantity of the inventory item that is available for In-Store Pickup at one or more of the merchant&#39;s physical stores. In-Store Pickup is only available to large merchants selling on the US, UK, Germany, and Australia sites.
 * @package     EbayInventoryApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class AvailabilityTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Availability"
     */
    public function testAvailability()
    {
    }

    /**
     * Test attribute "pickup_at_location_availability"
     */
    public function testPropertyPickupAtLocationAvailability()
    {
    }

    /**
     * Test attribute "ship_to_location_availability"
     */
    public function testPropertyShipToLocationAvailability()
    {
    }
}
