<?php
/**
 * BestOfferTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EbayInventoryApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace EbayInventoryApi;

use PHPUnit\Framework\TestCase;

/**
 * BestOfferTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used by the bestOfferTerms container, which is used if the seller would like to support the Best Offer feature on their listing.
 * @package     EbayInventoryApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class BestOfferTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BestOffer"
     */
    public function testBestOffer()
    {
    }

    /**
     * Test attribute "auto_accept_price"
     */
    public function testPropertyAutoAcceptPrice()
    {
    }

    /**
     * Test attribute "auto_decline_price"
     */
    public function testPropertyAutoDeclinePrice()
    {
    }

    /**
     * Test attribute "best_offer_enabled"
     */
    public function testPropertyBestOfferEnabled()
    {
    }
}
