<?php
/**
 * IntervalTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EbayInventoryApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace EbayInventoryApi;

use PHPUnit\Framework\TestCase;

/**
 * IntervalTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used by the intervals container to define the opening and closing times of a store&#39;s working day. Local time (in Military format) is used, with the following format: hh:mm:ss.
 * @package     EbayInventoryApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class IntervalTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Interval"
     */
    public function testInterval()
    {
    }

    /**
     * Test attribute "close"
     */
    public function testPropertyClose()
    {
    }

    /**
     * Test attribute "open"
     */
    public function testPropertyOpen()
    {
    }
}
