<?php
/**
 * InventoryLocationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  EbayInventoryApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace EbayInventoryApi;

use PHPUnit\Framework\TestCase;

/**
 * InventoryLocationTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used by the updateInventoryLocation call to update operating hours, special hours, phone number, and other minor details of an inventory location.
 * @package     EbayInventoryApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class InventoryLocationTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InventoryLocation"
     */
    public function testInventoryLocation()
    {
    }

    /**
     * Test attribute "location_additional_information"
     */
    public function testPropertyLocationAdditionalInformation()
    {
    }

    /**
     * Test attribute "location_instructions"
     */
    public function testPropertyLocationInstructions()
    {
    }

    /**
     * Test attribute "location_web_url"
     */
    public function testPropertyLocationWebUrl()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "operating_hours"
     */
    public function testPropertyOperatingHours()
    {
    }

    /**
     * Test attribute "phone"
     */
    public function testPropertyPhone()
    {
    }

    /**
     * Test attribute "special_hours"
     */
    public function testPropertySpecialHours()
    {
    }
}
