<?php
/**
 * InventoryItemGroupApiTest
 * PHP version 5
 *
 * @category Class
 * @package  EbayInventoryApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace EbayInventoryApi;

use \EbayInventoryApi\Configuration;
use \EbayInventoryApi\ApiException;
use \EbayInventoryApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * InventoryItemGroupApiTest Class Doc Comment
 *
 * @category Class
 * @package  EbayInventoryApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class InventoryItemGroupApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createOrReplaceInventoryItemGroup
     *
     * .
     *
     */
    public function testCreateOrReplaceInventoryItemGroup()
    {
    }

    /**
     * Test case for deleteInventoryItemGroup
     *
     * .
     *
     */
    public function testDeleteInventoryItemGroup()
    {
    }

    /**
     * Test case for getInventoryItemGroup
     *
     * .
     *
     */
    public function testGetInventoryItemGroup()
    {
    }
}
