<?php
/**
 * LocationApiTest
 * PHP version 5
 *
 * @category Class
 * @package  EbayInventoryApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Inventory API
 *
 * The Inventory API is used to create and manage inventory, and then to publish and manage this inventory on an eBay marketplace. There are also methods in this API that will convert eligible, active eBay listings into the Inventory API model.
 *
 * The version of the OpenAPI document: 1.9.0
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace EbayInventoryApi;

use \EbayInventoryApi\Configuration;
use \EbayInventoryApi\ApiException;
use \EbayInventoryApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * LocationApiTest Class Doc Comment
 *
 * @category Class
 * @package  EbayInventoryApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class LocationApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test case for createInventoryLocation
     *
     * .
     *
     */
    public function testCreateInventoryLocation()
    {
    }

    /**
     * Test case for deleteInventoryLocation
     *
     * .
     *
     */
    public function testDeleteInventoryLocation()
    {
    }

    /**
     * Test case for disableInventoryLocation
     *
     * .
     *
     */
    public function testDisableInventoryLocation()
    {
    }

    /**
     * Test case for enableInventoryLocation
     *
     * .
     *
     */
    public function testEnableInventoryLocation()
    {
    }

    /**
     * Test case for getInventoryLocation
     *
     * .
     *
     */
    public function testGetInventoryLocation()
    {
    }

    /**
     * Test case for getInventoryLocations
     *
     * .
     *
     */
    public function testGetInventoryLocations()
    {
    }

    /**
     * Test case for updateInventoryLocation
     *
     * .
     *
     */
    public function testUpdateInventoryLocation()
    {
    }
}
